### ISSUE TITLE
Test Model eos6hy3

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos6hy3#2]
Hi @carcablop and @pauline-banye !

Please can you test out this model on Colab and CLI?

**Comment by carcablop** [comment]
Hi @GemmaTuron 
This model run in the CLI successfully

[eos6hy3_predict.csv](https://github.com/ersilia-os/eos6hy3/files/10495616/eos6hy3_predict.csv)

[log_predict_eos6hy3.log](https://github.com/ersilia-os/eos6hy3/files/10495617/log_predict_eos6hy3.log)

this model run in the Colab successfully. 


[eos6hy3_output.csv](https://github.com/ersilia-os/eos6hy3/files/10495622/eos6hy3_output.csv)

**Comment by paulinebanye** [comment]
@GemmaTuron 
### MODEL TEST FOR EOS6HY3

## CLI
- [x]  Model eos6hy3 fetched, served and predicted successfully on the CLI.
- [X] Model was predicted using a list of smiles and a single smile 
[eos6hy3_fetch.log](https://github.com/ersilia-os/eos6hy3/files/10496025/eos6hy3_fetch.log)
[eos6hy3_predict.csv](https://github.com/ersilia-os/eos6hy3/files/10496127/eos6hy3_predict.csv)
[eos6hy3_list_predict.csv](https://github.com/ersilia-os/eos6hy3/files/10496133/eos6hy3_list_predict.csv)

## COLAB
- [x]  Model eos6hy3 fetched, served and predicted successfully on colab
[eos6hy3_output.csv](https://github.com/ersilia-os/eos6hy3/files/10495954/eos6hy3_output.csv)
https://colab.research.google.com/drive/1hqpMbpR3isKQ2caB7loWsyJi8iFziWpg?usp=sharing

**Comment by GemmaTuron** [comment]
@DhanshreeA and @miquelduranfrigola !

The model seems to be running fine but the Action fails at test time. We should find out why
